# 网站基本信息
title: EIT NLP课题组
subtitle: 宁波东方理工大学自然语言处理课题组
description: >-
  我们是宁波东方理工大学自然语言处理课题组，致力于推动变革性研究，
  专注于信息检索、多模态学习和链式推理等前沿方向。

# 网站URL配置  
url: https://eit-nlp.github.io
baseurl: ""

# 社交媒体链接
github: eit-nlp
email: contact@eit-nlp.org
wechat: EIT-NLP

# 改为Greene Lab模板的标准配置：
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# 网站主题色彩
theme_color: "#1976d2"